config/routes.rb
ETwoOne::Application.routes.draw do
  resources :accounts, :only => [:create, :update, :show]

  match '/learn-more' => 'pages#learn', :as => 'learn'
  match '/make-a-suggestion' => 'pages#suggestion', :as => 'suggestion'

  root :to => 'pages#splash'
end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id          :integer         not null, primary key
#  name        :string(255)
#  screen_name :string(255)
#  twitter_id  :integer
#  created_at  :datetime
#  updated_at  :datetime
#  location    :string(255)
#  description :string(255)
#

require 'net/http'
require 'json/ext'

class Account < ActiveRecord::Base
  attr_accessible :screen_name

  validates :screen_name, :presence => true
  validate :screen_name_exists
  before_save :get_info
  after_save :populate

  has_many :tweets

  USER_URI = "http://api.twitter.com/1/users/show.json?screen_name="
  STATUS = "http://api.twitter.com/1/statuses/user_timeline.json?screen_name="
  COUNT = 200

  private

    def screen_name_exists
      check_url = USER_URI + screen_name
      res = Net::HTTP.get_response(URI.parse(check_url))
      if res.code.to_i != 200
        errors.add(:screen_name, "That Twitter account does not exist")
      end
    end

    def get_info
      uri = USER_URI + screen_name
      res = Net::HTTP.get(URI.parse(uri))
      data = JSON.parse(res)
      self.name = data["name"]
      self.location = data["location"]
      self.description = data["description"]
      self.twitter_id = data["id"]
    end

    def populate
      # grab 200 of the most recent tweets
      uri = STATUS + screen_name + "&count=#{COUNT}"
      res = Net::HTTP.get(URI.parse(uri))
      data = JSON.parse(res)
      # examine each tweet
      data.map do |t|
        # determine if there's a link. If yes, save it down. If no, move on
        if t["text"] =~ /http:\/\//
          params = { :content => t["text"], :time => t["created_at"] }
          self.tweets.create!(params)
        end
      end
    end
end

app/models/link.rb
# == Schema Information
#
# Table name: links
#
#  id               :integer         not null, primary key
#  url              :string(255)
#  site_description :string(255)
#  created_at       :datetime
#  updated_at       :datetime

require 'net/http'

class Link < ActiveRecord::Base
  attr_accessible :url
  before_save :pull_info
  has_many :tweets

  private

    def pull_info
      # pull out meta info from the site to form site description
      # pull out meta info from the site to form keywords
    end
end

app/models/tweet.rb
# == Schema Information
#
# Table name: tweets
#
#  id         :integer         not null, primary key
#  link_id    :integer
#  time       :datetime
#  content    :string(255)
#  created_at :datetime
#  updated_at :datetime
#  account_id :integer
#

class Tweet < ActiveRecord::Base
  attr_accessible :time, :content
  before_save :add_link
  belongs_to :account
  belongs_to :link

  LINK_REG = /(http:\/\/[\w\.\/\?\&\=\+\%]+\b)/i

  private

    def add_link
      LINK_REG.match(self.content)
      uri_str = fetch($1)
      link = nil
      if Link.find_by_url(uri_str)
        link = Link.find_by_url(uri_str)
      else
        link = Link.create!(:url => uri_str)
      end
      self.link_id = link.id
    end
    
    # This code is taken from ruby-doc.org/stdlib-1.9.2/libdoc/net/http/rdoc/
    # Net/HTTP.html
    def fetch(uri_str, limit = 10)
      raise ArgumentError, 'HTTP redirect too deep' if limit == 0

      uri = URI.parse(URI.encode(uri_str))
      http_session = Net::HTTP.new(uri.host, uri.port)
      http_session.use_ssl = true if uri.port == 443
      res = nil
      http_session.start { |http|
        res = http.request_get(uri.request_uri)
      }

      case res
      when Net::HTTPSuccess     then uri_str
      when Net::HTTPRedirection 
        if res.code.to_i != 302
          fetch(res['location'], limit - 1)
        else
          uri_str
        end
      else
        res.error!
      end
    end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def create

  end

  def update
  end

  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def splash
    @account = Account.new
  end

  def learn
  end

  def suggestion
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/accounts/show.html.erb
<p>This is the show page</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= yield :head %>
    <%= stylesheet_link_tag 'style', :media => 'screen' %>
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <script src="/javascripts/jquery-1.6.3.min.js">
    </script>
    <header>
      <%= image_tag("disclog-logo.jpg", :alt => "Disclog", :id => "logo") %>
      <%= image_tag("sign-in-mouse-off.jpg", :alt => "Sign In",
                                             :id => "sign-in") %>
    </header>
    <%= yield %>
    <footer>
      <span class="copyright">Disclog (c)2011</span>
      <nav>
        <ul>
          <li><%= link_to "Join", '#'%> |&nbsp;</li>
          <li><%= link_to "Learn More", learn_path %> |&nbsp;</li>
          <li><%= link_to "Make a Suggestion", suggestion_path %></li>
        </ul>
      </nav>
    </footer>
  </body>
</html>

app/views/pages/learn.html.erb
<h1>Pages#Learn</h1>
<p>You can find me at app/pages/learn.html.erb</p>

app/views/pages/splash.html.erb
<% content_for :head do %>
  <title>Disclog</title>
  <%= stylesheet_link_tag 'splash', :media => 'screen' %>
<% end %>
<script>
  $(document).ready(function(){
    var mainHeight = $("body").height()-50;
    $("section.main").height(mainHeight);
  });
</script>
<section class="main">
  <div class="main-left">
    <div class="floater" id="floater_left"></div>
    <div class="centered" id="centered_left">
      <p><span id="disclog">Disclog</span> is a new way to explore the web</p>
      <br />
      <p>
        Catalog the links of the people you <i>follow</i> to better discover 
        the web
      </p>
    </div>
  </div>
  <div class="main-right">
    <div class="floater" id="floater_right"></div>
    <div class="centered" id="centered_right">
      <p>Enter a Twitter handle and try it out!</p>
      <br />
      <%= form_for @account do |f| %>
        <%= f.text_field :screen_name %>
        <input id="button" type="button" value="Go" />
      <% end %>
    </div>
  </div>
</section>  

app/views/pages/suggestion.html.erb
<h1>Pages#suggestion</h1>
<p>Find me in app/views/pages/suggestion.html.erb</p>